export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERTISEMENTS_LOADED = 'ADVERTISEMENTS_LOADED';
export const ADVERTISEMENT_DELETE = 'ADVERTISEMENT_DELETE';

export const ADVERTISEMENT_NEW_REQUEST = 'ADVERTISEMENT_NEW_REQUEST';
export const ADVERTISEMENT_NEW_SUCCESSS = 'ADVERTISEMENT_NEW_SUCCESSS';
export const ADVERTISEMENT_NEW_FAILURE = 'ADVERTISEMENT_NEW_FAILURE';
